### ISSUE TITLE
Does locuscompare run on all UNIX platforms?

### ISSUE THREAD

**Issue by opalhuang** [boxiangliu/locuscompare#3]
Dear Boxiang,

I have been trying to use locuscompareR package. When I ran the command

main(in_fn1 = gwas_fn, in_fn2 = eqtl_fn, title1 = 'CAD GWAS', title2 = 'Coronary Artery eQTL')

I got the following error:
Error in loadNamespace(name) : there is no package called ‘RMySQL’

So I tried to install RMySQL, but had the following error.

> install.packages('RMySQL')
Installing package into ‘/home/trg710/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://mirrors.dotsrc.org/cran/src/contrib/RMySQL_0.10.17.tar.gz'
Content type 'application/octet-stream' length 52273 bytes (51 KB)
==================================================
downloaded 51 KB

 installing *source* package ‘RMySQL’ ...
** package ‘RMySQL’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=
Using PKG_LIBS=-lmysqlclient
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because no mysql client library was found. Try installing:
 * deb: libmariadbclient-dev | libmariadb-client-lgpl-dev (Debian, Ubuntu)
 * rpm: mariadb-connector-c-devel | mariadb-devel | mysql-devel (Fedora, CentOS, RHEL)
 * csw: mysql56_dev (Solaris)
 * brew: mariadb-connector-c (OSX)
If you already have a mysql client library installed, verify that either
mariadb_config or mysql_config is on your PATH. If these are unavailable
you can also set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘RMySQL’
* removing ‘/home/trg710/R/x86_64-pc-linux-gnu-library/3.5/RMySQL’

I would like to know if locuscompareR can be installed on all UNIX platforms?

Best regards,
Opal

**Comment by boxiangliu** [comment]
Hello Opal, 

Yes. It should run on all platforms which have R. 

You will need to first install mysql client. 

> no mysql client library was found. Try installing:
> 
> deb: libmariadbclient-dev | libmariadb-client-lgpl-dev (Debian, Ubuntu)
> rpm: mariadb-connector-c-devel | mariadb-devel | mysql-devel (Fedora, CentOS, RHEL)
> csw: mysql56_dev (Solaris)
> brew: mariadb-connector-c (OSX)

**Comment by boxiangliu** [comment]
Closing issue.
