### ISSUE TITLE
Which reference panel is used in LocusCompare?

### ISSUE THREAD

**Issue by opalhuang** [boxiangliu/locuscompare#4]
Dear Boxiang,

Would you be able to let me know which reference panel is used in locuscompare? Is it 1000 Genome Phase 3 or UKBB?

Best regards,
Opal

**Comment by mikegloudemans** [comment]
Hi Opal,

It's 1000 Genomes Phase 3. (Also, as you may have seen, while viewing the plots for a single locus, there's a "population" option that allows you to color LD using just a subset of the full 2504.)

**Comment by opalhuang** [comment]
HI Mike,

Thank you. Is there any plan to upgrade the reference panel to UKBB? If so, when would that be?

Best,
Opal
