### ISSUE TITLE
UKBB reference panel

### ISSUE THREAD

**Issue by opalhuang** [boxiangliu/locuscompare#5]
HI Mike,

Is there any plan to upgrade the reference panel from 1000 Genome phase 3 to UKBB? If so, when would that be?

Best,
Opal

**Comment by boxiangliu** [comment]
Dear Opal,

We currently do not plan to add the UKBB reference genome. Sorry about that. 

Boxiang

**Comment by boxiangliu** [comment]
Closing issue. Re-open if needed.
