### ISSUE TITLE
mySQL error when running standalone locuscompareR

### ISSUE THREAD

**Issue by Julia-Elsayed-Moustafa** [boxiangliu/locuscompare#6]
Hello,

I've been attempting to run locuscompareR on an HPC cluster. I've successfully installed the locuscomparer library, but I receive the following error every time I try to generate the locuscompare plot:

locuscompare(in_fn1=gwas_fn, in_fn2=eqtl_fn, title1="T2D", title2="eQTL_Nominal")

Error in .local(conn, statement, ...) : 
  could not run statement: MySQL server has gone away

both gwas_fn and eqtl_fn are dataframes loaded into my environment, and contain the appropriate columns.  

Do you have any suggestions for how I can resolve this error?

Thanks very much,
Julia

**Comment by mikegloudemans** [comment]
This thread on the R-specific repository might be helpful: https://github.com/boxiangliu/locuscomparer/issues/5

**Comment by boxiangliu** [comment]
Hello @Julia-Elsayed-Moustafa, could you tell me how large are your data.frames? The SQL server might shut when it has received a large request.

**Comment by Julia-Elsayed-Moustafa** [comment]
Hi Boxiang,

Thanks very much for your quick reply. My data frames are indeed very large, I was using the full set of nominal results for both the GWAS and the eQTL - the GWAS DF is 21,635,867 rows, while the eQTL DF is 120,421,356 rows. If size is the issue, would you recommend following your pipeline for colocalization tests first (https://bitbucket.org/mgloud/production_coloc_pipeline/) ?

Thanks again for your help with this.

All the best,
Julia

**Comment by boxiangliu** [comment]
I would recommend breaking up the dataframe to smaller parts (i.e. by gene) and run them in parallel. 

This will not only avoid timeouts but also speed up the plotting.

**Comment by mikegloudemans** [comment]
To elaborate on what Bosh said above, the reason this takes so long is that the program pulls LD statistics for all SNPs in the dataframe from an online database. This doesn't take too long if it's just one gene and its cis-eQTL region, but will take very very long to do it for an entire genome!

**Comment by boxiangliu** [comment]
Closing issue. Please re-open if needed.
